# Generated by Django 6.0.4 on 2026-09-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_experience_years_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='project_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project')),
            ],
        ),
    ]
