# Generated by Django 6.0.4 on 2026-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatgroup_callsession_chatmessage_chatgroupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment_url',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('FILE', 'File'), ('NONE', 'None')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
