# Generated by Django 6.0.4 on 2026-09-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_chatmessage_attachment_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment_file',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment_name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment_type',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_text',
            field=models.TextField(),
        ),
    ]
