# Generated by Django 6.0.4 on 2026-09-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('NEEDS_REVISION', 'Needs Revision'), ('COMPLETED', 'Completed')], default='TODO', max_length=20),
        ),
    ]
