# Generated by Django 6.0.4 on 2026-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='requirements_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='selfie_image',
            field=models.FileField(blank=True, null=True, upload_to='task_selfies/'),
        ),
    ]
