# Generated by Django 6.0.4 on 2026-09-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_task_reporter_email_task_reporter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='visited_person_company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='visited_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='visited_person_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='visited_person_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
